apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - scanjob.yml
  - orchestration-job.yml
  - scanjob-parameter.yml
  - test-job.yml
  - delete-test-products-template.yml 


commonLabels:
    app.kubernetes.io/name: clusterscanner
    app.kubernetes.io/instance: test
