apiVersion: v1
kind: ConfigMap
metadata:
  namespace: clusterscanner
  name: scanjob-env-parameter
  labels:
    # Note that this label is required for the informer to detect this ConfigMap.
    workflows.argoproj.io/configmap-type: Parameter
data:
  SKOPEO_COPY_PARAMETER: "" # e.g. "--src-tls-verify=false "
  SKOPEO_INSPECT_PARAMETER: "" # e.g. "tls-verify=false "
  NO_PROXY: "kubernetes.default.svc"
  JAVA_OPTS: "" # e.g. proxy
