---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cluster-image-scanner-images
  namespace: clusterscanner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cluster-image-scanner-scandata
  namespace: clusterscanner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
