version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: "github-actions"
    directory: "/" # Location of your GitHub Actions workflows
    schedule:
      interval: "weekly"
