repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: mixed-line-ending
      args: [ --fix=lf ]
    - id: trailing-whitespace
      args: [ --markdown-linebreak-ext=* ]
    - id: check-json
    - id: check-merge-conflict
    - id: detect-aws-credentials
      args: [ --allow-missing-credentials ]
    - id: double-quote-string-fixer
    - id: end-of-file-fixer

- repo: https://github.com/pre-commit-ci/pre-commit-ci-config
  rev: v1.6.1
  hooks:
    - id: check-pre-commit-ci-config

- repo: https://github.com/renovatebot/pre-commit-hooks
  rev: 40.26.1
  hooks:
    - id: renovate-config-validator
