apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: orchestration-
spec:
  onExit: notify-teams
  serviceAccountName: clusterscanner
  ttlStrategy:
    secondsAfterSuccess: 3600
    secondsAfterFailure: 86400
  artifactRepositoryRef:
    configMap: artifact-repositories
    key: default-v1
  entrypoint: main
  arguments:
    parameters:
      - name: scanId
        value: "{{ workflow.creationTimestamp.Y }}{{ workflow.creationTimestamp.m }}{{ workflow.creationTimestamp.d }}_{{ workflow.creationTimestamp.H }}{{ workflow.creationTimestamp.M }}{{ workflow.creationTimestamp.S }}"
  templates:
    - name: main
      steps:
        - - name: fetch-image-list
            template: fetch-image-list
        - - name: run-subflow
            template: subflow
            arguments:
              artifacts:
                - name: imageList
                  from: "{{steps.fetch-image-list.outputs.artifacts.image-list-merged}}"
              parameters:
                - name: REGISTRY_SECRET
                  value: clusterscannerregistry
                - name: DEPENDENCY_SCAN_CM
                  value: dependency-check-db
                - name: DEFECTDOJO_CM
                  value: defectdojo-test
                - name: DEFECTDOJO_SECRETS
                  value: defectdojo-test


    - name: fetch-image-list
      outputs:
        artifacts:
          - name: image-lists
            path: /clusterscanner/out
            archive:
              none: {}
          - name: image-list-merged
            path: /clusterscanner/out/merged/merged.json
            archive:
              none: {}
      volumes:
        - name: image-source-list
          configMap:
            name: image-source-list
        - name: github
          secret:
            secretName: github
        - name: tmp
          emptyDir: {}
      script:
        image: quay.io/sdase/clusterscanner-base:2
        imagePullPolicy: Always
        volumeMounts:
          - name: github
            mountPath: /clusterscanner/github/github_private_key.pem
            subPath: github_private_key.pem
          - name: image-source-list
            mountPath: /clusterscanner/image-source-list
          - name: tmp
            mountPath: /clusterscanner/out
        env:
          - name: GITHUB_KEY_FILE_PATH
            value: /clusterscanner/github/github_private_key.pem
        envFrom:
          - secretRef:
              name: "github"
        command: [/bin/bash]
        workingDir: /clusterscanner
        source: |
          set -e
          source auth.bash # > /dev/null 2>&1
          sp_authorize #> /dev/null 2>&1
          i=1
          for repofile in /clusterscanner/image-source-list/*; do
            repourl=$(cat $repofile)
            echo "$i: $repofile $repourl"
            sp_getfile $repourl /clusterscanner/out/$i.json #> /dev/null 2>&1#
            if [ $(grep 'image' /clusterscanner/out/$i.json | wc -l) -eq 0 ]; then
              echo "Could not get repo $repourl from ($repofile) or the repos doesn't include images"
              exit 1
            fi
            ((i=i+1))
          done
          mkdir -p /clusterscanner/out/merged
          jq -s 'flatten' /clusterscanner/out/*.json > /clusterscanner/out/merged/merged.json
          sed -i 's#"scm_source_branch": null#"scm_source_branch": "notset"#g' /clusterscanner/out/merged/merged.json
          echo "done"
          exit 0

    - name: subflow
      inputs:
        parameters:
          - name: REGISTRY_SECRET
          - name: DEPENDENCY_SCAN_CM
          - name: DEFECTDOJO_CM
          - name: DEFECTDOJO_SECRETS
        artifacts:
          - name: imageList
            path: /clusterscanner/imageList.json
      script:
        image: quay.io/sdase/clusterscanner-imagecollector:2
        imagePullPolicy: Always
        command: [/bin/bash]
        workingDir: /clusterscanner
        source: |
          cat /clusterscanner/imageList.json | jq -cMr '.[] | @base64' > /clusterscanner/imageListSeparated.json
          cat /clusterscanner/imageListSeparated.json | while read line
          do
            echo "YXBpVmVyc2lvbjogYXJnb3Byb2ouaW8vdjFhbHBoYTEKa2luZDogV29ya2Zsb3cKbWV0YWRhdGE6CiAgZ2VuZXJhdGVOYW1lOiBzY2Fuam9iLSMjI2Vudmlyb25tZW50IyMjLSMjI25hbWVzcGFjZSMjIy0jIyN0ZWFtIyMjLQogIGxhYmVsczoKICAgIGNsdXN0ZXJzY2FubmVyLnNkYS5zZS9zY2FuLWlkOiAjIyNTQ0FOX0lEIyMjCnNwZWM6CiAgYXJndW1lbnRzOgogICAgcGFyYW1ldGVyczoKICAgICAgLSBuYW1lOiBSRUdJU1RSWV9TRUNSRVQKICAgICAgICB2YWx1ZTogIyMjUkVHSVNUUllfU0VDUkVUIyMjCiAgICAgIC0gbmFtZTogREVQRU5ERU5DWV9TQ0FOX0NNCiAgICAgICAgdmFsdWU6ICMjI0RFUEVOREVOQ1lfU0NBTl9DTSMjIwogICAgICAtIG5hbWU6IERFRkVDVERPSk9fQ00KICAgICAgICB2YWx1ZTogIyMjREVGRUNURE9KT19DTSMjIwogICAgICAtIG5hbWU6IERFRkVDVERPSk9fU0VDUkVUUwogICAgICAgIHZhbHVlOiAjIyNERUZFQ1RET0pPX1NFQ1JFVFMjIyMKICAgICAgLSBuYW1lOiBTQ0FOX0lECiAgICAgICAgdmFsdWU6ICMjI1NDQU5fSUQjIyMKICAgICAgLSBuYW1lOiB0ZWFtCiAgICAgICAgdmFsdWU6ICMjI3RlYW0jIyMKICAgICAgLSBuYW1lOiBlbnZpcm9ubWVudAogICAgICAgIHZhbHVlOiAjIyNlbnZpcm9ubWVudCMjIwogICAgICAtIG5hbWU6IG5hbWVzcGFjZQogICAgICAgIHZhbHVlOiAjIyNuYW1lc3BhY2UjIyMKICAgICAgLSBuYW1lOiBzY21fc291cmNlX2JyYW5jaAogICAgICAgIHZhbHVlOiAjIyNzY21fc291cmNlX2JyYW5jaCMjIwogICAgICAtIG5hbWU6IGltYWdlCiAgICAgICAgdmFsdWU6ICMjI2ltYWdlIyMjCiAgICAgIC0gbmFtZTogaW1hZ2VfaWQKICAgICAgICB2YWx1ZTogIyMjaW1hZ2VfaWQjIyMKICAgICAgLSBuYW1lOiBzbGFjawogICAgICAgIHZhbHVlOiAjIyNzbGFjayMjIwogICAgICAtIG5hbWU6IGlzX3NjYW5fbGlmZXRpbWUKICAgICAgICB2YWx1ZTogIyMjaXNfc2Nhbl9saWZldGltZSMjIwogICAgICAtIG5hbWU6IGlzX3NjYW5fZGlzdHJvbGVzcwogICAgICAgIHZhbHVlOiAjIyNpc19zY2FuX2Rpc3Ryb2xlc3MjIyMKICAgICAgLSBuYW1lOiBpc19zY2FuX21hbHdhcmUKICAgICAgICB2YWx1ZTogIyMjaXNfc2Nhbl9tYWx3YXJlIyMjCiAgICAgIC0gbmFtZTogaXNfc2Nhbl9kZXBlbmRlbmN5X2NoZWNrCiAgICAgICAgdmFsdWU6ICMjI2lzX3NjYW5fZGVwZW5kZW5jeV9jaGVjayMjIwogICAgICAtIG5hbWU6IGlzX3NjYW5fcnVuYXNyb290CiAgICAgICAgdmFsdWU6ICMjI2lzX3NjYW5fcnVuYXNyb290IyMjCiAgICAgIC0gbmFtZTogc2Nhbl9saWZldGltZV9tYXhfZGF5cwogICAgICAgIHZhbHVlOiAjIyNzY2FuX2xpZmV0aW1lX21heF9kYXlzIyMjCiAgd29ya2Zsb3dUZW1wbGF0ZVJlZjoKICAgIG5hbWU6IHNjYW4taW1hZ2Utam9iCg==" | base64 -d > /clusterscanner/template.yml
            DATA_JSON=$(echo $line | base64 -d | jq -cM .)
            sed -i "s~###REGISTRY_SECRET###~{{ inputs.parameters.REGISTRY_SECRET }}~" /clusterscanner/template.yml
            sed -i "s~###DEPENDENCY_SCAN_CM###~{{ inputs.parameters.DEPENDENCY_SCAN_CM }}~" /clusterscanner/template.yml
            sed -i "s~###DEFECTDOJO_CM###~{{ inputs.parameters.DEFECTDOJO_CM }}~" /clusterscanner/template.yml
            sed -i "s~###DEFECTDOJO_SECRETS###~{{ inputs.parameters.DEFECTDOJO_SECRETS }}~" /clusterscanner/template.yml
            sed -i "s~###SCAN_ID###~{{ workflow.creationTimestamp.Y }}{{ workflow.creationTimestamp.m }}{{ workflow.creationTimestamp.d }}-{{ workflow.creationTimestamp.H }}{{ workflow.creationTimestamp.M }}{{ workflow.creationTimestamp.S }}~" /clusterscanner/template.yml
            sed -i "s~###team###~$(echo ${DATA_JSON} | jq -r .team)~" /clusterscanner/template.yml
            sed -i "s~###environment###~$(echo ${DATA_JSON} | jq -r .environment)~" /clusterscanner/template.yml
            sed -i "s~###namespace###~$(echo ${DATA_JSON} | jq -r .namespace)~" /clusterscanner/template.yml
            sed -i "s~###scm_source_branch###~$(echo ${DATA_JSON} | jq -r .scm_source_branch)~" /clusterscanner/template.yml
            sed -i "s~###image###~$(echo ${DATA_JSON} | jq -r .image)~" /clusterscanner/template.yml
            sed -i "s~###image_id###~$(echo ${DATA_JSON} | jq -r .image_id)~" /clusterscanner/template.yml
            sed -i "s~###slack###~$(echo ${DATA_JSON} | jq -r .slack)~" /clusterscanner/template.yml
            sed -i "s~###is_scan_lifetime###~$(echo ${DATA_JSON} | jq -r .is_scan_lifetime)~" /clusterscanner/template.yml
            sed -i "s~###is_scan_distroless###~$(echo ${DATA_JSON} | jq -r .is_scan_distroless)~" /clusterscanner/template.yml
            sed -i "s~###is_scan_malware###~$(echo ${DATA_JSON} | jq -r .is_scan_malware)~" /clusterscanner/template.yml
            sed -i "s~###is_scan_dependency_check###~$(echo ${DATA_JSON} | jq -r .is_scan_dependency_check)~" /clusterscanner/template.yml
            sed -i "s~###is_scan_runasroot###~$(echo ${DATA_JSON} | jq -r .is_scan_runasroot)~" /clusterscanner/template.yml
            sed -i "s~###scan_lifetime_max_days###~$(echo ${DATA_JSON} | jq -r .scan_lifetime_max_days)~" /clusterscanner/template.yml
            cat /clusterscanner/template.yml
            kubectl create -n clusterscanner -f /clusterscanner/template.yml
          done
          while [[ "$(argo list --running -n clusterscanner -l clusterscanner.sda.se/scan-id={{ workflow.creationTimestamp.Y }}{{ workflow.creationTimestamp.m }}{{ workflow.creationTimestamp.d }}-{{ workflow.creationTimestamp.H }}{{ workflow.creationTimestamp.M }}{{ workflow.creationTimestamp.S }} | wc -l)" -gt 1 ]]; do
            echo "There are still workflows running, waiting another 10 seconds"
            sleep 10
          done

    - name: notify-teams
      volumes:
        - name: scandata
          persistentVolumeClaim:
            claimName: clusterscanner-scandata
      container:
        image: quay.io/sdase/clusterscanner-notifier:2
        volumeMounts:
          - name: scandata
            mountPath: /clusterscanner/data
            subPath: "{{ workflow.parameters.scanId }}"
        imagePullPolicy: Always
        env:
          - name: SLACK_CLI_TOKEN
            valueFrom:
              secretKeyRef:
                name: slacktoken
                key: SLACK_CLI_TOKEN
          - name: smtp
            valueFrom:
              secretKeyRef:
                name: email
                key: smtp
          - name: smtp-auth
            valueFrom:
              secretKeyRef:
                name: email
                key: smtp-auth
          - name: smtp-auth-user
            valueFrom:
              secretKeyRef:
                name: email
                key: smtp-auth-user
          - name:  smtp-auth-password
            valueFrom:
              secretKeyRef:
                name: email
                key: smtp-auth-password
          - name: ENFORCE_SLACK_CHANNEL
            value: "#security-notifications-test"
