apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: orchestration-
spec:
  serviceAccountName: clusterscanner
  ttlStrategy:
    secondsAfterSuccess: 3600
    secondsAfterFailure: 86400
  artifactRepositoryRef:
    configMap: artifact-repositories
    key: default-v1
  entrypoint: main
  arguments:
    parameters:
      - name: scanId
        value: "{{ workflow.creationTimestamp.Y }}{{ workflow.creationTimestamp.m }}{{ workflow.creationTimestamp.d }}-{{ workflow.creationTimestamp.H }}{{ workflow.creationTimestamp.M }}{{ workflow.creationTimestamp.S }}"
      - name: gitSecretName
        value: "github"
      - name: imageSourceListConfigMapName
        value: "image-source-list"
      - name: registrySecretName
        value: "registry-default"
      - name: defectDojoConfigMapName
        value: "defectdojo"
      - name: slackTokenSecretName
        value: "slacktoken"
      - name: emailSecretName
        value: "email"
      - name: dependencyCheckDbConfigMapName
        value: "dependency-check-db"
      - name: enforceSlackChannel
        value: "#security-notifications-test"
      - name: newVersionImageFilter
        value: "quay.io/sdase/|swaggerapi/petstore"
      - name: dependencyCheckSuppressionsConfigMapName
        value: "suppressions-sda"
      - name: allResultsGitTarget
        value: ""
      - name: baseImageName
        value: "quay.io/sdase/cluster-image-scanner-base:2"
      - name: defectDojoClientImageName
        value: "{{ workflow.parameters.defectDojoClientImageName }}"
      - name: scanDistrolessImageName
        value: "{{ workflow.parameters.scanDistrolessImageName }}"
      - name: scanDependencyCheckImageName
        value: "{{ workflow.parameters.scanDependencyCheckImageName }}"
      - name: scanMalwareImageName
        value: "{{ workflow.parameters.scanMalwareImageName }}"
      - name: scanRootImageName
        value: "{{ workflow.parameters.scanRootImageName }}"
      - name: scanLifetimeImageName
        value: "{{ workflow.parameters.scanLifetimeImageName }}"
      - name: scanNewVersion
        value: "{{ workflow.parameters.scanNewVersion }}"
      - name: imageSourceFetcherImageName
        value: "{{ workflow.parameters.imageSourceFetcherImageName }}"
      - name: workflowRunnerImageName
        value: "{{ workflow.parameters.workflowRunnerImageName }}"

  templates:
    - name: main
      steps:
        - - name: orchestration-job
            templateRef:
              name: orchestration-job-template
              template: main
