apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: orchestration-
spec:
  onExit: notify-teams
  serviceAccountName: clusterscanner
  ttlStrategy:
    secondsAfterSuccess: 3600
    secondsAfterFailure: 86400
  artifactRepositoryRef:
    configMap: artifact-repositories
    key: default-v1
  entrypoint: main
  arguments:
    parameters:
      - name: scanId
        value: "{{ workflow.creationTimestamp.Y }}{{ workflow.creationTimestamp.m }}{{ workflow.creationTimestamp.d }}-{{ workflow.creationTimestamp.H }}{{ workflow.creationTimestamp.M }}{{ workflow.creationTimestamp.S }}"
      - name: maxSubJobs
        value: 10
  templates:
    - name: main
      steps:
        - - name: fetch-image-list
            template: fetch-image-list
        - - name: run-subflow
            template: subflow
            arguments:
              artifacts:
                - name: imageList
                  from: "{{steps.fetch-image-list.outputs.artifacts.image-list-merged}}"
              parameters:
                - name: REGISTRY_SECRET
                  value: registry-sda-default
                - name: DEPENDENCY_SCAN_CM
                  value: dependency-check-db
                - name: DEFECTDOJO_CM
                  value: defectdojo-test
                - name: DEFECTDOJO_SECRETS
                  value: defectdojo-test


    - name: fetch-image-list
      outputs:
        artifacts:
          - name: image-lists
            path: /clusterscanner/out
            archive:
              none: {}
          - name: image-list-merged
            path: /clusterscanner/out/merged/merged.json
            archive:
              none: {}
      volumes:
        - name: image-source-list
          configMap:
            name: image-source-list
        - name: github
          secret:
            secretName: github
        - name: tmp
          emptyDir: {}
      script:
        image: quay.io/sdase/clusterscanner-base:2
        imagePullPolicy: Always
        volumeMounts:
          - name: github
            mountPath: /clusterscanner/github/github_private_key.pem
            subPath: github_private_key.pem
          - name: image-source-list
            mountPath: /clusterscanner/image-source-list
          - name: tmp
            mountPath: /clusterscanner/out
        env:
          - name: GITHUB_KEY_FILE_PATH
            value: /clusterscanner/github/github_private_key.pem
        envFrom:
          - secretRef:
              name: "github"
        command: [/bin/bash]
        workingDir: /clusterscanner
        source: |
          set -e
          source auth.bash # > /dev/null 2>&1
          sp_authorize #> /dev/null 2>&1
          i=1
          for repofile in /clusterscanner/image-source-list/*; do
            repourl=$(cat $repofile)
            echo "$i: $repofile $repourl"
            sp_getfile $repourl /clusterscanner/out/$i.json #> /dev/null 2>&1#
            if [ $(grep 'image' /clusterscanner/out/$i.json | wc -l) -eq 0 ]; then
              echo "Could not get repo $repourl from ($repofile) or the repos doesn't include images"
              exit 1
            fi
            ((i=i+1))
          done
          mkdir -p /clusterscanner/out/merged
          jq -s 'flatten' /clusterscanner/out/*.json > /clusterscanner/out/merged/merged.json
          sed -i 's#"scm_source_branch": null#"scm_source_branch": "notset"#g' /clusterscanner/out/merged/merged.json
          echo "done"
          exit 0

    - name: subflow
      inputs:
        parameters:
          - name: REGISTRY_SECRET
          - name: DEPENDENCY_SCAN_CM
          - name: DEFECTDOJO_CM
          - name: DEFECTDOJO_SECRETS
        artifacts:
          - name: imageList
            path: /clusterscanner/imageList.json
      script:
        image: quay.io/sdase/clusterscanner-imagecollector:2
        imagePullPolicy: Always
        command: [/bin/bash]
        workingDir: /clusterscanner
        source: |
          set -e
          cat /clusterscanner/imageList.json | jq -cMr '.[] | @base64' > /clusterscanner/imageListSeparated.json
          cat /clusterscanner/imageListSeparated.json | while read line
          do
            echo "YXBpVmVyc2lvbjogYXJnb3Byb2ouaW8vdjFhbHBoYTEKa2luZDogV29ya2Zsb3cKbWV0YWRhdGE6CiAgZ2VuZXJhdGVOYW1lOiBzY2Fuam9iLSMjI2Vudmlyb25tZW50IyMjLSMjI25hbWVzcGFjZSMjIy0jIyN0ZWFtIyMjLQogIGxhYmVsczoKICAgIGNsdXN0ZXJzY2FubmVyLnNkYS5zZS9zY2FuLWlkOiAiIyMjU0NBTl9JRCMjIyIKc3BlYzoKICBhcmd1bWVudHM6CiAgICBwYXJhbWV0ZXJzOgogICAgICAtIG5hbWU6IFJFR0lTVFJZX1NFQ1JFVAogICAgICAgIHZhbHVlOiAiIyMjUkVHSVNUUllfU0VDUkVUIyMjIgogICAgICAtIG5hbWU6IERFUEVOREVOQ1lfU0NBTl9DTQogICAgICAgIHZhbHVlOiAiIyMjREVQRU5ERU5DWV9TQ0FOX0NNIyMjIgogICAgICAtIG5hbWU6IERFRkVDVERPSk9fQ00KICAgICAgICB2YWx1ZTogIiMjI0RFRkVDVERPSk9fQ00jIyMiCiAgICAgIC0gbmFtZTogREVGRUNURE9KT19TRUNSRVRTCiAgICAgICAgdmFsdWU6ICIjIyNERUZFQ1RET0pPX1NFQ1JFVFMjIyMiCiAgICAgIC0gbmFtZTogU0NBTl9JRAogICAgICAgIHZhbHVlOiAiIyMjU0NBTl9JRCMjIyIKICAgICAgLSBuYW1lOiB0ZWFtCiAgICAgICAgdmFsdWU6ICIjIyN0ZWFtIyMjIgogICAgICAtIG5hbWU6IGFwcG5hbWUKICAgICAgICB2YWx1ZTogIiMjI2FwcG5hbWUjIyMiCiAgICAgIC0gbmFtZTogZW52aXJvbm1lbnQKICAgICAgICB2YWx1ZTogIiMjI2Vudmlyb25tZW50IyMjIgogICAgICAtIG5hbWU6IG5hbWVzcGFjZQogICAgICAgIHZhbHVlOiAiIyMjbmFtZXNwYWNlIyMjIgogICAgICAtIG5hbWU6IHNjbV9zb3VyY2VfYnJhbmNoCiAgICAgICAgdmFsdWU6ICIjIyNzY21fc291cmNlX2JyYW5jaCMjIyIKICAgICAgLSBuYW1lOiBpbWFnZQogICAgICAgIHZhbHVlOiAiIyMjaW1hZ2UjIyMiCiAgICAgIC0gbmFtZTogaW1hZ2VfaWQKICAgICAgICB2YWx1ZTogIiMjI2ltYWdlX2lkIyMjIgogICAgICAtIG5hbWU6IHNsYWNrCiAgICAgICAgdmFsdWU6ICIjIyNzbGFjayMjIyIKICAgICAgLSBuYW1lOiBpc19zY2FuX2xpZmV0aW1lCiAgICAgICAgdmFsdWU6ICIjIyNpc19zY2FuX2xpZmV0aW1lIyMjIgogICAgICAtIG5hbWU6IGlzX3NjYW5fZGlzdHJvbGVzcwogICAgICAgIHZhbHVlOiAiIyMjaXNfc2Nhbl9kaXN0cm9sZXNzIyMjIgogICAgICAtIG5hbWU6IGlzX3NjYW5fbWFsd2FyZQogICAgICAgIHZhbHVlOiAiIyMjaXNfc2Nhbl9tYWx3YXJlIyMjIgogICAgICAtIG5hbWU6IGlzX3NjYW5fZGVwZW5kZW5jeV9jaGVjawogICAgICAgIHZhbHVlOiAiIyMjaXNfc2Nhbl9kZXBlbmRlbmN5X2NoZWNrIyMjIgogICAgICAtIG5hbWU6IGlzX3NjYW5fcnVuYXNyb290CiAgICAgICAgdmFsdWU6ICIjIyNpc19zY2FuX3J1bmFzcm9vdCMjIyIKICAgICAgLSBuYW1lOiBzY2FuX2xpZmV0aW1lX21heF9kYXlzCiAgICAgICAgdmFsdWU6ICIjIyNzY2FuX2xpZmV0aW1lX21heF9kYXlzIyMjIgogIHdvcmtmbG93VGVtcGxhdGVSZWY6CiAgICBuYW1lOiBzY2FuLWltYWdlLWpvYgo=" | base64 -d > /clusterscanner/template.yml
            DATA_JSON=$(echo $line | base64 -d | jq -cM .)
            if [[ "$(echo "${DATA_JSON}" | jq -r '.skip')" == "true" ]]; then
              image=$(echo "${DATA_JSON}" | jq '.image')
              echo "Skipping Image: $(echo ${DATA_JSON} | jq -r '.image') Namespace: $(echo ${DATA_JSON} | jq -r '.namespace') Environment: $(echo ${DATA_JSON} | jq -r '.environment')"
              continue
            fi
            sed -i "s~###REGISTRY_SECRET###~{{ inputs.parameters.REGISTRY_SECRET }}~" /clusterscanner/template.yml
            sed -i "s~###DEPENDENCY_SCAN_CM###~{{ inputs.parameters.DEPENDENCY_SCAN_CM }}~" /clusterscanner/template.yml
            sed -i "s~###DEFECTDOJO_CM###~{{ inputs.parameters.DEFECTDOJO_CM }}~" /clusterscanner/template.yml
            sed -i "s~###DEFECTDOJO_SECRETS###~{{ inputs.parameters.DEFECTDOJO_SECRETS }}~" /clusterscanner/template.yml
            sed -i "s~###SCAN_ID###~{{ workflow.parameters.scanId }}~" /clusterscanner/template.yml
            sed -i "s~###team###~$(echo ${DATA_JSON} | jq -r .team)~" /clusterscanner/template.yml
            sed -i "s~###appname###~$(echo ${DATA_JSON} | jq -r .appname)~" /clusterscanner/template.yml
            sed -i "s~###environment###~$(echo ${DATA_JSON} | jq -r .environment)~" /clusterscanner/template.yml
            sed -i "s~###namespace###~$(echo ${DATA_JSON} | jq -r .namespace)~" /clusterscanner/template.yml
            sed -i "s~###scm_source_branch###~$(echo ${DATA_JSON} | jq -r .scm_source_branch)~" /clusterscanner/template.yml
            sed -i "s~###image###~$(echo ${DATA_JSON} | jq -r .image)~" /clusterscanner/template.yml
            sed -i "s~###image_id###~$(echo ${DATA_JSON} | jq -r .image_id)~" /clusterscanner/template.yml
            sed -i "s~###slack###~$(echo ${DATA_JSON} | jq -r .slack)~" /clusterscanner/template.yml
            sed -i "s~###is_scan_lifetime###~$(echo ${DATA_JSON} | jq -r .is_scan_lifetime)~" /clusterscanner/template.yml
            sed -i "s~###is_scan_distroless###~$(echo ${DATA_JSON} | jq -r .is_scan_distroless)~" /clusterscanner/template.yml
            sed -i "s~###is_scan_malware###~$(echo ${DATA_JSON} | jq -r .is_scan_malware)~" /clusterscanner/template.yml
            sed -i "s~###is_scan_dependency_check###~$(echo ${DATA_JSON} | jq -r .is_scan_dependency_check)~" /clusterscanner/template.yml
            sed -i "s~###is_scan_runasroot###~$(echo ${DATA_JSON} | jq -r .is_scan_runasroot)~" /clusterscanner/template.yml
            sed -i "s~###scan_lifetime_max_days###~$(echo ${DATA_JSON} | jq -r .scan_lifetime_max_days)~" /clusterscanner/template.yml
            cat /clusterscanner/template.yml
            kubectl create -n clusterscanner -f /clusterscanner/template.yml
            while [[ "$(argo list --running -n clusterscanner -l clusterscanner.sda.se/scan-id={{ workflow.parameters.scanId }} | tail --lines=+2 | wc -l)" -gt {{ workflow.parameters.maxSubJobs }} ]]; do
              echo "There are 10 scans running already, waiting for some to finish"
              sleep 10
            done
          done
          while [[ "$(argo list --running -n clusterscanner -l clusterscanner.sda.se/scan-id={{ workflow.parameters.scanId }} | tail --lines=+2 | wc -l)" -gt 0 ]]; do
            echo "There are still scans running, waiting another 10 seconds"
            sleep 10
          done
          echo "All scans have finished"

    - name: notify-teams
      volumes:
        - name: scandata
          persistentVolumeClaim:
            claimName: clusterscanner-scandata
      container:
        image: quay.io/sdase/clusterscanner-notifier:2
        volumeMounts:
          - name: scandata
            mountPath: /clusterscanner/data
            subPath: "{{ workflow.parameters.scanId }}"
        imagePullPolicy: Always
        env:
          - name: SLACK_CLI_TOKEN
            valueFrom:
              secretKeyRef:
                name: slacktoken
                key: SLACK_CLI_TOKEN
          - name: smtp
            valueFrom:
              secretKeyRef:
                name: email
                key: smtp
          - name: smtp-auth
            valueFrom:
              secretKeyRef:
                name: email
                key: smtp-auth
          - name: smtp-auth-user
            valueFrom:
              secretKeyRef:
                name: email
                key: smtp-auth-user
          - name:  smtp-auth-password
            valueFrom:
              secretKeyRef:
                name: email
                key: smtp-auth-password
          - name: ENFORCE_SLACK_CHANNEL
            value: "#security-notifications-test"
