apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: orchestration-
spec:
  serviceAccountName: clusterscanner
  ttlStrategy:
    secondsAfterSuccess: 3600
    secondsAfterFailure: 86400
  artifactRepositoryRef:
    configMap: artifact-repositories
    key: default-v1
  entrypoint: main
  arguments:
    parameters:
      - name: scanId
        value: "{{ workflow.creationTimestamp.Y }}{{ workflow.creationTimestamp.m }}{{ workflow.creationTimestamp.d }}-{{ workflow.creationTimestamp.H }}{{ workflow.creationTimestamp.M }}{{ workflow.creationTimestamp.S }}"
  templates:
    - name: main
      steps:
        - - name: orchestration-job
            templateRef:
              name: orchestration-job-template
              template: main
            arguments:
              parameters:
                - name: scanId
                  value: "{{ workflow.parameters.scanId }}"
