apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: orchestration-
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: clusterscanner
  ttlStrategy:
    secondsAfterSuccess: 3600
    secondsAfterFailure: 7200
  artifactRepositoryRef:
    configMap: artifact-repositories
    key: default-v1
  entrypoint: main
  arguments:
    parameters:
      - name: scanId
        value: "{{ workflow.creationTimestamp.Y }}{{ workflow.creationTimestamp.m }}{{ workflow.creationTimestamp.d }}-{{ workflow.creationTimestamp.H }}{{ workflow.creationTimestamp.M }}{{ workflow.creationTimestamp.S }}"
      - name: gitSecretName
        value: "github"
      - name: imageSourceListConfigMapName
        value: "image-source-list"
      - name: registrySecretName
        value: "registry-default"
      - name: defectDojoConfigMapName
        value: "defectdojo"
      - name: slackTokenSecretName
        value: "slacktoken"
      - name: emailSecretName
        value: "email"
      - name: dependencyCheckDbConfigMapName
        value: "dependency-check-db"
      - name: enforceSlackChannel
        value: "#security-notifications-test"
      - name: newVersionImageFilter
        value: "quay.io/sdase/|swaggerapi/petstore"
      - name: dependencyCheckSuppressionsConfigMapName
        value: "suppressions-sda"
      - name: allResultsGitTarget
        value: "" # "github.com/SDA-SE/cluster-image-scanner-test-results"
      - name: imageRegistryBase
        value: "quay.io/sdase"
      - name: clusterImageScannerImageTag
        value: "###clusterImageScannerImageTag###"
  templates:
    - name: main
      steps:
        - - name: delete-test-products
            templateRef:
              name: delete-test-products-template
              template: main
        - - name: orchestration-job
            templateRef:
              name: orchestration-job-template
              template: main
        - - name: test-job
            templateRef:
              name: test-job-template
              template: main