apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ClusterImageScanner
  title: Cluster Image Scanner
  description: |
    Discover vulnerabilities and container image misconfiguration in production environments.
  tags:
    - security-stack
  annotations:
    backstage.io/techdocs-ref: url:https://github.com/SDA-SE/cluster-image-scanner/tree/master
  links:
    - url: https://github.com/SDA-SE/cluster-image-scanner/
      title: Github Repository
spec:
  type: service
  owner: security-journey
  system: cluster-image-scanner
  lifecycle: production
