apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-repositories
  namespace: clusterscanner
data:
  default-v1: |
    s3:
      bucket: local
      endpoint: minio-hl.clusterscanner.svc:9000
      insecure: true
      accessKeySecret:
        name: minio-auth
        key: accesskey
      secretKeySecret:
        name: minio-auth
        key: secretkey
