apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: clusterscanner
generatorOptions:
  disableNameSuffixHash: true

resources:
  - ../../deployment/overlays/test-local/
  - minio.auth.yml
  - minio.tenant.yml
  - auth.yml

commonLabels:
  app.kubernetes.io/name: clusterscanner
  app.kubernetes.io/instance: org.sda

patches:
  - path: artifacts.yml
