apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: clusterscanner
generatorOptions:
  disableNameSuffixHash: true

resources:
  - auth.yml
  - sa.yaml

commonLabels:
  app.kubernetes.io/name: clusterscanner
  app.kubernetes.io/instance: org.sda

#patches:
#  - path: artifacts.yml
