---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-default-workflow
  namespace: clusterscanner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflow
subjects:
  - kind: ServiceAccount
    name: clusterscanner
    namespace: clusterscanner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clusterscanner
  namespace: clusterscanner