apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - orchestration-job.yml
  - scanjob.yml

commonLabels:
    app.kubernetes.io/name: clusterscanner
    app.kubernetes.io/instance: test
