name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create and push an image
        run: |
          chmod +x ./build.sh
          if [ "${GITHUB_REF##*/}" == "master" ]; then
            VERSION="2.0.$GITHUB_RUN_NUMBER"
          else
            BRANCH_TO_DOCKER=$(echo ${GITHUB_REF##*/} | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]//g')
            VERSION="$BRANCH_TO_DOCKER-$GITHUB_RUN_NUMBER"
          fi
          sudo ./build.sh "quay.io" "sdase" "clusterscanner-scan-malware" "$VERSION" ${{ secrets.QUAY_IO_CLUSTERSCANNER_USERNAME }} ${{ secrets.QUAY_IO_CLUSTERSCANNER_TOKEN }} true
     
