apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  annotations:
    contact.sdase.org/team: "security-journey"
    sdase.org/description: "The cluster-image-scanner discovers vulnerabilities and container image misconfiguration in production environments."
