apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflow
  namespace: argocd
spec:
  destination:
    namespace: clusterscanner
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/argoproj/argo-workflows.git
    targetRevision: v3.4.4
    path: manifests/namespace-install
  project: clusterscanner
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
