apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-upload-repository
  namespace: cluster-image-scanner-image-collector
data:
  collector.upload.github.appid: "GH_APP_ID_PLACEHOLDER"
  collector.upload.github.installlationid: "GH_INSTALLATION_ID_PLACEHOLDER"
  collector.namespacemapping: |
    {
      "teams": [
        {
          "namespaces": [
            {"namespace_filter": "argo", "description": "used for deployment"},
            {"namespace_filter": "kube-", "description": "kube-system is the namespace for objects created by the Kubernetes system, containing services which are needed to run Kubernetes"},
            {"namespace_filter": "kube-", "description": "kube-system is the namespace for objects created by the Kubernetes system, containing services which are needed to run Kubernetes"},
            {"namespace_filter": "minio", "description": "minio to store workflow artifacts"}

          ],
          "configurations": {
            "skip": "true",
            "scan_lifetime_max_days": "90",
            "is_scan_lifetime": "true",
            "is_scan_baseimage_lifetime": "true",
            "is_scan_distroless": "true",
            "is_scan_malware": "false",
            "is_scan_runasroot": "true",
            "slack": "#security-notifications-test",
            "container_type": "third-party",
            "team": "operations"
          }
        }
      ]
    }
