apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-scan-collector
  namespace: cluster-image-scanner-image-collector
spec:
  template:
    spec:
      activeDeadlineSeconds: 3600
      serviceAccountName: image-collector
      automountServiceAccountToken: true # mount cluster-scan
      restartPolicy: Never
      containers:
        - name: cluster-scan-image-collector
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            runAsUser: 1001
          image: "quay.io/sdase/cluster-image-scanner-imagecollector:2.0"
          imagePullPolicy: Always
          env:
            - name: CLUSTER_NAME
              value: "lord-of-the-rings"
            - name: DEFAULT_SKIP
              value: "true"
            - name: GIT_REPOSITORY
              value: "github.com/pagel-pro/cluster-image-scanner-test-targets.git"
            - name: GH_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: collector-upload-repository
                  key: collector.upload.github.appid
            - name: GH_INSTALLATION_ID
              valueFrom:
                configMapKeyRef:
                  name: collector-upload-repository
                  key: collector.upload.github.installlationid
            - name: NAMESPACE_MAPPINGS
              valueFrom:
                configMapKeyRef:
                  name: collector-upload-repository
                  key: collector.namespacemapping
          resources:
            limits:
              cpu: 0.8
              memory: 124Mi
      volumes:
        - name: collector-upload-repository
          configMap:
            name: collector-upload-repository
