apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cluster-image-scanner-image-collector

resources:
  - namespace.yaml
  - configmap.yaml
  - job.yml
  - service-account-authorization.yaml

patches:
  - secret-volume.yaml

