apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-scan-collector
  namespace: cluster-image-scanner-image-collector
spec:
  template:
    spec:
      containers:
        - name: cluster-scan-image-collector
          volumeMounts:
            - name: github
              mountPath: "/etc/github"
              readOnly: true
      volumes:
        - name: github
          secret:
            secretName: github
            items:
              - key: keyfile
                path: keyfile
