apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cluster-scan-collector
  namespace: cluster-image-scanner-image-collector
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cluster-scan-image-collector
              volumeMounts:
                - name: github
                  mountPath: "/etc/github"
                  readOnly: true
          volumes:
            - name: github
              secret:
                secretName: github
                items:
                  - key: keyfile
                    path: keyfile
