apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cleanup-enforced-delete-pvc-wf-scandata
  namespace: clusterscanner
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  timezone: Europe/Berlin
  activeDeadlineSeconds: 3600
  workflowSpec:
    artifactRepositoryRef:
      configMap: artifact-repositories
      key: default-v1
    entrypoint: pvc-cleanup
    templates:
      - name: pvc-cleanup
        volumes:
          - name: scandata
            persistentVolumeClaim:
              claimName: cluster-image-scanner-scandata
        script:
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          image: quay.io/sdase/clusterscanner-base:2
          volumeMounts:
            - name: scandata
              mountPath: /clusterscanner/data
          imagePullPolicy: IfNotPresent
          command: [bash]
          source: |
            /usr/bin/whoami

            SECONDS_IN_WEEK=$((7 * 24 * 60 * 60))

            CURRENT_TIME=$(date +%s)

            for file in /clusterscanner/data/*; do
              if [ -f "$file" ]; then
                LAST_ACCESS_TIME=$(stat -c %X "$file")
            
                TIME_DIFF=$((CURRENT_TIME - LAST_ACCESS_TIME))
            
                if [ "${TIME_DIFF}" -gt "${SECONDS_IN_WEEK}" ]; then
                  rm -f "$file"
                  echo "File $file has been deleted"
                fi
              fi
            done
            echo "Will delete empty directories in /clusterscanner/data/"
            find /clusterscanner/data/* -type d -empty -delete
            echo "Size of /clusterscanner/data/"
            du -sh /clusterscanner/data/
