apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cleanup-enforced-delete-pvc-wf-images
  namespace: clusterscanner
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  timezone: Europe/Berlin
  activeDeadlineSeconds: 3600
  workflowSpec:
    artifactRepositoryRef:
      configMap: artifact-repositories
      key: default-v1
    entrypoint: pvc-cleanup
    templates:
      - name: pvc-cleanup
        volumes:
          - name: images
            persistentVolumeClaim:
              claimName: cluster-image-scanner-images
        script:
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          image: quay.io/sdase/cluster-image-scanner-base:2
          volumeMounts:
            - name: images
              mountPath: /clusterscanner/images
          imagePullPolicy: IfNotPresent
          command: [bash]
          source: |
            set -e

            /usr/bin/whoami

            KEEP_FILE_DAYS=7

            du -sh /clusterscanner/images/ || true

            for cleanupPath in $(find /clusterscanner/images/* -maxdepth 2 -mindepth 2 -mtime +${KEEP_FILE_DAYS}); do
                echo "Removing ${cleanupPath}"
                rm -Rf "${cleanupPath}" || echo "Error: Could not delete ${cleanupPath}"
            done
            find /clusterscanner/images/ -maxdepth 2 -empty -type d -delete

            echo "Size of /clusterscanner/images/"
            du -sh /clusterscanner/images/
            exit 0
