apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cleanup-pvc-wf-scandata
  namespace: clusterscanner
spec:
  schedule: "23 14 * * *"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 0
  timezone: Europe/Berlin
  activeDeadlineSeconds: 3600
  workflowSpec:
    entrypoint: pvc-cleanup
    templates:
      - name: pvc-cleanup-scandata
        volumes:
          - name: scandata
            persistentVolumeClaim:
              claimName: cluster-image-scanner-scandata
        script:
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          image: quay.io/sdase/cluster-image-scanner-base:2
          volumeMounts:
            - name: scandata
              mountPath: /clusterscanner/data
          imagePullPolicy: Always
          command: [bash]
          env:
            - name: MAX_DAYS
              value: "7"
          source: |
            set -e
            /usr/bin/whoami
            du -sh /clusterscanner/images/data || true

            for cleanupPath in $(find /clusterscanner/data/ -name *.json -mtime +${MAX_DAYS}); do
                echo "Removing ${cleanupPath}"
                rm -Rf ${cleanupPath} || true # folders have owner rights issues
            done
            find /clusterscanner/data/ -empty -type d -delete

            echo "done"
            exit 0
