---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clusterscanner-images
  namespace: clusterscanner
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clusterscanner-scandata
  namespace: clusterscanner
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
