---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clusterscanner-images
  namespace: clusterscanner
  annotations:
    app.kubernetes.io/name: clusterscanner
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clusterscanner-scandata
  namespace: clusterscanner
  annotations:
    app.kubernetes.io/name: clusterscanner
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
