name: "Build image"
description: "Builds an publishes an image to quay.io"
inputs:
  image-path:
    description: "Path in repository to image build dir"
    required: true
  image-name:
    description: "Name of the image to build an publish"
    required: true
  registry-user:
    description: "Username for pushing the image to a registry"
    required: true
  registry-token:
    description: "Token for pushing the image to a registry"
    required: true
runs:
  using: "composite"
  steps:
    - name: create and push an image
      shell: bash
      run: |
        source ./test_actions/library.bash
        echo "GITHUB_BASE_REF${GITHUB_BASE_REF##*/}"
        exit;
        cd ${{ inputs.image-path }}
        chmod +x ./build.sh
        sudo ./build.sh "quay.io" "sdase" "${{ inputs.image-name }}" "${VERSION}" "${{ inputs.registry-user }}" "${{ inputs.registry-token }}" true
