---
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "image-metadata-orchestrator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "image-metadata-orchestrator.labels" .  | nindent 4 }}
  annotations:
    {{- if .Values.serviceAccount.awsRoleArn}}
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.awsRoleArn }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-default-workflow-artifacts
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflow
subjects:
  - kind: ServiceAccount
    name: {{ include "image-metadata-orchestrator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
