---
apiVersion: v1
kind: Secret
metadata:
  name: defectdojo
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "image-metadata-orchestrator.labels" .  | nindent 4 }}
data:
  DD_TOKEN: {{ required "A defectdojo access token is required." .Values.defectdojo.token | b64enc }}
