#---
apiVersion: v1
kind: Secret
metadata:
  name: registry-sda-default
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "image-metadata-orchestrator.labels" .  | nindent 4 }}
data:
  auth.json: {{ .Values.registry.authJson | b64enc }}
