#---
apiVersion: v1
kind: Secret
metadata:
  name: slacktoken
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "image-metadata-orchestrator.labels" .  | nindent 4 }}
data:
  SLACK_CLI_TOKEN: {{ .Values.slack.cliToken | b64enc }}
