apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cleanup-enforced-delta-pvc-wf-images
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "{{ .Values.cleanup.schedule }}"
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: {{ .Values.cleanup.startingDeadlineSeconds }}
  timezone: Europe/Berlin
  activeDeadlineSeconds: {{ .Values.cleanup.activeDeadlineSeconds }}
  workflowSpec:
    entrypoint: pvc-cleanup
    templates:
      - name: pvc-cleanup
        volumes:
          - name: images
            persistentVolumeClaim:
              claimName: cluster-image-scanner-images
        script:
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          image: {{ .Values.cleanup.image.repo }}:{{ .Values.cleanup.image.tag }}
          volumeMounts:
            - name: images
              mountPath: /clusterscanner/images
          imagePullPolicy: IfNotPresent
          command: [python3]
          source: |
            import os
            import time
            import shutil
            KEEP_DAYS=7
            print('Deleting in /clusterscanner/images')
            for root, dirs, files in os.walk('/clusterscanner/images'):
                if 'manifest.json' in files:
                   if time.time() - os.path.getatime(root) > KEEP_DAYS  * 24 * 60 * 60:
                        print(f"Directory {root} has been changed  more than {KEEP_DAYS} days ago. Deleting.")
                        shutil.rmtree(root)
