apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: registry-edithcare-default
  namespace: clusterscanner
spec:
  encryptedData:
    auth.json: AgBfIjxuhEXBT7h5gZziTHCC5QXNzM3td4pPurvLEzbn+G300aRKlReoHods9f1lljm/qHqmhCTUFqyadKicaIEkBxn59GgDL9yNsK3Cxrr0s8sI1DfTdR0H2+YBDH5haUiVbUgcKuLGidqg8A0TS3ZKYRpN0qCZJ8l00xYTXb/8HbUsM1iflkgKWXk0xyXRnewtsitnfflQZQU7oxfqLgPVn/67tpNfrJwy+GUI2XJNZBUGg/7puAkQVuSQfnrdzizpwrptdtn/Z3hLcvnb5AN1MZt4D5NI0gTFCTqEEBFHxxSD6IJJyqZxXu/Vp75onKufhQLoUUwNSVZmFozArRibvMGnSZfeIrfl5D6I8A433ZugcNGU90UyPrw3yCL1q8Ax3CDL+L3G8Y6zvCwUzkqWfm8BP4/wVszCy6+xa4FTRUXFDj1CQPhJxFJg6sd0MNLoVCwH8KJUnlZd7Xsjz8TD2HtxYt5bYiG4XiLVEMba6axnwuzMk5UtjdrOTe5e81kd1hqWIBl4MLi7trS/OKQKaySwHPm/MYBIAjYVMoSs3nRk4PZSyDUVAX8+vB5mrqIaAxtw/UAffG93+8Ie7XP/X/IdIDpGAejam9uAY0ALyY7AzsXnSsgcgVbXsT0evUU7RiWkTmYjCdBLZG9oXR2jAJpjBHg0p5UGaJzNIwgkCiz/wEYNn08KsAIG/2A3mMOyuiDNaY5H8M/Gv0ta1AZZsa4q5hTCIQNfi1DkZ5Ovs03vdeXxJTKp1gZTzmQTMkaL92YNx8PJ5xJQD2tdiuMaziXpCSatLo3kGufhPafuAvHInGJMoAXJ/+14MsSC2T7/qpdXTlzCCnxj7KiNurpWC0/Ox93BxzGfN3nXQuxIqCrZpwX88NeqaZrhOaMm94uIWJBXDEXiIHJQzp56jWR+qmD9HYmwmQpW4HWsxgPMaRV+fr93ICTOueZOJ/QPM5Wk1Ped7uSs5ghVWYxg9rfiRPzzo88n0Pqm5JkyoDp6r6c3/ymaIDmLBqVdZEdUoY0xdtEPPZaRg1MS0KIzQBemwEet42OgrY3JSEFdrSXad9En1oZ0Xecl6WZDc5desA==
  template:
    metadata:
      creationTimestamp: null
      name: registry-edithcare-default
      namespace: clusterscanner
