---
apiVersion: v1
kind: Secret
metadata:
  name: api-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-image-scanner-orchestrator.labels" .  | nindent 4 }}
data:
  S3_API_KEY: "{{ required "An API key is required." .Values.credentials.apikey | b64enc }}"
  S3_API_SIGNATURE:  "{{ required "An API signature is required." .Values.credentials.signature | b64enc }}"
