---
# SA to be used in workflow
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-service-account-name
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: clusterscanner
    {{- include "cluster-image-scanner-orchestrator.labels" .  | nindent 4 }}
data:
  name: "{{ .Values.serviceAccount.name }}"
