---
apiVersion: v1
kind: Secret
metadata:
  name: dependency-track
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-image-scanner-orchestrator.labels" .  | nindent 4 }}
data:
  DEPENDENCY_TRACK_KEY: {{ required "A dependencytrack access key is required." .Values.dependencytrack.key | b64enc }}
