---
apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-image-scanner-orchestrator.labels" .  | nindent 4 }}
data:
  GH_APP_ID: {{ .Values.github.appId | b64enc }}
  GH_APP_LOGIN: {{ .Values.github.appLogin | b64enc }}
  GH_INSTALLATION_ID: {{ .Values.github.installationId | b64enc }}
  github_private_key.pem: {{ .Values.github.privateKeyPem | b64enc }}
