{{- if .Values.isLocal }}
apiVersion: v1
kind: Secret
metadata:
  name: minio-auth
  namespace:  {{ .Release.Namespace }}
stringData:
  accesskey: "testtesttest"
  secretkey: "testtesttest"
{{- end }}
