apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orchestrator-workflow
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-image-scanner-orchestrator.labels" .  | nindent 4 }}
  annotations:
    checkov.io/skip1: CKV_K8S_21=The default namespace should not be used
    checkov.io/skip2: CKV_K8S_49=Minimize wildcard use in Roles and ClusterRoles
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "patch"]
  - apiGroups:
      - ""
    resources: ["pods"]
    verbs: ["get", "watch"]
  - apiGroups: [ "argoproj.io"]
    resources: ["workflows"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: s3-account-binding-cis-wf
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-image-scanner-orchestrator.labels" . | nindent 4 }}
  annotations:
    checkov.io/skip1: CKV_K8S_21=The default namespace should not be used
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: orchestrator-workflow
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
