apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sda-product-security-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-image-scanner-orchestrator.labels" .  | nindent 4 }}
  annotations:
    checkov.io/skip1: CKV_K8S_21=The default namespace should not be used
    checkov.io/skip2: CKV_K8S_49=Minimize wildcard use in Roles and ClusterRoles
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sda-product-security-role-binding
  labels:
    {{- include "cluster-image-scanner-orchestrator.labels" .  | nindent 4 }}
  annotations:
    checkov.io/skip1: CKV_K8S_21=The default namespace should not be used
subjects:
  - kind: User
    name: sda-product-security
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: sda-product-security-role
  apiGroup: rbac.authorization.k8s.io