apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../base-template
  - ../../base-pvc
  - defectdojo-test.secret.yml
  - defectdojo-test.cm.yml
  - slack.yml
  - rbac.yml
  - s3.api.secret.yml
  - s3.api.cm.yml

generatorOptions:
  labels:
    app.kubernetes.io/name: clusterscanner
    app.kubernetes.io/instance: test

patches:
  - path: artifacts.yml

secretGenerator:
  - name: email
    namespace: clusterscanner
    behavior: replace
    type: Secret
    envs:
      - config-source/email.env
  - name: defectdojo-test
    namespace: clusterscanner
    behavior: replace
    type: Secret
    envs:
      - config-source/defectdojo-test.secret.env
  - name: defectdojo
    namespace: clusterscanner
    behavior: replace
    type: Secret
    envs:
      - config-source/defectdojo.secret.env
  - name: s3-cred
    namespace: clusterscanner
    behavior: replace
    type: Secret
    envs:
      - config-source/s3.api.secret.env

  - name: slacktoken
    namespace: clusterscanner
    behavior: replace
    type: Secret
    envs:
      - config-source/slack.env
  - name: github
    namespace: clusterscanner
    behavior: replace
    type: Secret
    envs:
      - config-source/github.env
    files:
      - config-source/github_private_key.pem
  - name: dependency-track
    namespace: clusterscanner
    behavior: replace
    envs:
      - config-source/dependency-track.secret.env

configMapGenerator:
  - name: dependency-check-db
    namespace: clusterscanner
    behavior: replace
    envs:
      - config-source/depcheck.env

  - name: image-source-list
    namespace: clusterscanner
    behavior: replace
    envs:
      - config-source/repolist.env

  - name: dependency-track
    namespace: clusterscanner
    behavior: replace
    envs:
      - config-source/dependency-track.cm.env

  - name: defectdojo
    namespace: clusterscanner
    behavior: replace
    envs:
      - config-source/defectdojo.cm.env

  - name: defectdojo-test
    namespace: clusterscanner
    behavior: replace
    envs:
      - config-source/defectdojo-test.cm.env
