apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: s3-workflow-secret
  namespace: clusterscanner
spec:
  encryptedData:
    accesskey: AgDQ9DBYXaFAV3xq3bKIZ9rwpXGmk98eP7mDQkH2YbjVlzrTa6MYH6Kxv9DNYr94G3sUlHQQBg/0pGVio/Wiv80/J252CnBoa21VT47I+NOoIPCbvxkMhT+EwOB/DKudh96U6uq2j2O++AVgRZb+mQlYxTDZxJ+UfXS5uJ26yQfPIBH2phFWKsVAA/LPsU9qAbtNx95PhqQU192tSZRMnZeDMDNSYka9h4+QsdfTfZAcYTA9/zw2xg9XMuaSP7MzFzQPGM2pOHuVOst5u1Dn8BhWmaAWDTEpCfgKFbbKvYRGhGZ92WyTwzS4u/NqZLqz0KlqZ+5wyMoHhyZcdCjRZMzlicEIO2lryj+Rn+K3KRFCjRpkdWoZPF89wfbjmJgaOCMSANXWqEraVhIWdfckvQDqNpHzqNbAiitLcKlGwd54xhN9OjoAKhyLOT390qlYOXx95ikdMfZGydntwcL+3d9Qu/fE2E5KGCsyFPWx4SahQpjo/C8JR36JVombCiyju2WqMu7N8Jib67Z0hlPE7kUFDYJ4Gx+96BviFBKiQ8EJ/WOg+2d5lR7ZGxX0z1z6K3RH8ZA45rqrBwQ4w+8TRod+fHnfh2fGdWfm2XJW+Mc2UB2MdoPp6SJLrAFwx+fZA8yjaGvERoQJyuDdHpTaPG6/GLnfvzH6tQp50c4EIsygubE/rw8S/TWBW/5p2z+hG/YUxXf+ID1pY3NdCS+oW6zMwZR/qQ==
    secretkey: AgAG1VVe1bvuOlMWpW6RKk/JVG+y9SgYxI4ogs70oEUEmV6it/l4x3pJH4t4ocgKqIxKr2vI1tlGdYDcjOCnwoPcQsb//INRUVof/0P9B/MV3pVMH6b1T2jEIsvVEnPRnP2/EzNFh/Bb92b4kv9KzN2fRJ7+RGMPQnN5XifKjHAi9MMtTV9y0+SfOuQWyqaYbw6khVmiBqdLHK+tswjCEAu1t0a86TKyXIMBuhudzrs2aHqZLQsWnT1leV3kBU/AH75/qfL1DEzve6QUhA2rXc6IUJDLTRAIcXPNB1Nn3KuKYGAjTu6NCA75Ia9LKozFpl4X1FVEQ7tUFW6B7pr+wBdtsxQPSHr1CulTRiLbzHELfIhqN524US+T04hIcO9kNnKqJZLX5pp7IEw8XzCKgUG9k+fS4adCZR50jAJrIapYyGU2JE9uYDrtnWVxNr7zccvV+grAGiPmJU6dQlQ65I1imUx0GsSiwJjTN8im+sDg/2bLUCn5j2mGMzbCTyOZpWkICUw0UUuWHo74o1/4+3i7ULKCpR6z9bPI/8sm6UY+Zaiysq6oFN2Kwl+3O/rzzkQ9p89cZBVWllZxZqGpstxHWQiBI3SBZbye0SY6p5/vHtM/1UD1AloEBj7hQQ/VDdEuLjDyxHjn6nwzFoxM4uAe4SXKk/hHd4tQoydS4lCEi8w+c5pFfR6Qiu8cXlJgQNcn14ubRvaUBDNOtY5PKrZ5e7Fwg53LwuLelYALUa7ncf9GMunnAePl
  template:
    metadata:
      creationTimestamp: null
      name: s3-workflow-secret
      namespace: clusterscanner
