name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  publish-docs:
    name: Build and publish docs
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      ENTITY_KIND: Component
      ENTITY_NAME: clusterscanner
    strategy:
      matrix:
        site:
          - directory: ./
            entity_name: clusterscanner
    container:
      image: quay.io/sdase/techdocs:1
    steps:
      - uses: actions/checkout@v2.3.4

      - name: build
        run: techdocs-cli generate --no-docker --verbose
        working-directory: ${{ matrix.site.directory }}

      - name: publish
        if: github.ref == 'refs/heads/master'
        run: techdocs-cli publish --publisher-type awsS3 --storage-name "$TECHDOCS_S3_BUCKET_NAME" --entity "$ENTITY"
        working-directory: ${{ matrix.site.directory }}
        env:
          TECHDOCS_S3_BUCKET_NAME: ${{ secrets.TECHDOCS_S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.TECHDOCS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TECHDOCS_S3_SECRET_ACCESS_KEY }}
          ENTITY: ${{ env.ENTITY_NAMESPACE || 'default' }}/${{ env.ENTITY_KIND || 'Component' }}/${{ env.ENTITY_COMPONENT }}