name: Build Image and Test with Minikube

on:
  push:
  pull_request:
  schedule:
    - cron: "30 6 * * *"
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: shellcheck
        uses: reviewdog/action-shellcheck@f627b974d3005f993dc36f46d2cdf2684be18e5c
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          path: "."
          pattern: "*.*sh"
          exclude: "./.git/*"
          shellcheck_flags: "--external-sources --exclude=SC1090,SC1091,SC2116,SC2015"

  changes:
    runs-on: ubuntu-latest
    if: "${{ (github.event_name == 'schedule') || !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork) }}"
    outputs:
      base: ${{ steps.filter.outputs.base }}
      imagesourcefetcher: ${{ steps.filter.outputs.imagesourcefetcher }}
      imagecollector: ${{ steps.filter.outputs.imagecollector }}
      notifier: ${{ steps.filter.outputs.notifier }}
      workflowrunner: ${{ steps.filter.outputs.workflowrunner }}
      dependencycheck: ${{ steps.filter.outputs.dependencycheck }}
      distroless: ${{ steps.filter.outputs.distroless }}
      lifetime: ${{ steps.filter.outputs.lifetime }}
      malware: ${{ steps.filter.outputs.malware }}
      runasroot: ${{ steps.filter.outputs.runasroot }}
      new-version: ${{ steps.filter.outputs.new-version }}
      syft: ${{ steps.filter.outputs.syft }}
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721
        id: filter
        with:
          base: "master" # ignored in PRs
          filters: |
            base:
              - 'images/base/**'
            imagesourcefetcher:
              - 'images/process/image-source-fetcher/**'
            imagecollector:
              - 'images/process/imagecollector/**'
            workflowrunner:
              - 'images/process/workflow-runner/**'
            notifier:
              - 'images/process/notifier/**'
            dependencycheck:
              - 'images/scan/dependency-check/**'
            distroless:
              - 'images/scan/distroless/**'
            lifetime:
              - 'images/scan/lifetime/**'
            malware:
              - 'images/scan/malware/**'
            runasroot:
              - 'images/scan/runasroot/**'
            new-version:
              - 'images/scan/new-version/**'
            syft:
              - 'images/scan/syft/**'

  changes_pr:
    runs-on: ubuntu-latest
    if: "github.event_name == 'pull_request' && !github.event.pull_request.head.repo.fork) }}"
    outputs:
      base: ${{ steps.filter.outputs.base }}
      imagesourcefetcher: ${{ steps.filter.outputs.imagesourcefetcher }}
      imagecollector: ${{ steps.filter.outputs.imagecollector }}
      notifier: ${{ steps.filter.outputs.notifier }}
      workflowrunner: ${{ steps.filter.outputs.workflowrunner }}
      dependencycheck: ${{ steps.filter.outputs.dependencycheck }}
      distroless: ${{ steps.filter.outputs.distroless }}
      lifetime: ${{ steps.filter.outputs.lifetime }}
      malware: ${{ steps.filter.outputs.malware }}
      runasroot: ${{ steps.filter.outputs.runasroot }}
      new-version: ${{ steps.filter.outputs.new-version }}
      syft: ${{ steps.filter.outputs.syft }}
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: dorny/paths-filter@b2feaf19c27470162a626bd6fa8438ae5b263721
        id: filter
        with:
          base: "master" # ignored in PRs
          filters: |
            base:
              - 'images/base/**'
            imagesourcefetcher:
              - 'images/process/image-source-fetcher/**'
            imagecollector:
              - 'images/process/imagecollector/**'
            workflowrunner:
              - 'images/process/workflow-runner/**'
            notifier:
              - 'images/process/notifier/**'
            dependencycheck:
              - 'images/scan/dependency-check/**'
            distroless:
              - 'images/scan/distroless/**'
            lifetime:
              - 'images/scan/lifetime/**'
            malware:
              - 'images/scan/malware/**'
            runasroot:
              - 'images/scan/runasroot/**'
            new-version:
              - 'images/scan/new-version/**'
            syft:
              - 'images/scan/syft/**'

  build_image_base:
    needs: changes, changes_pr
    runs-on: ubuntu-latest
    # do not execute for PRs that origin from forks due to security concerns and missing secrets
    if: "${{ (github.event_name == 'schedule') || (needs.changes.outputs.base == 'true' && !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork)) }}"
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: ./.github/actions/build_image
        with:
          image-path: images/base
          image-name: cluster-image-scanner-base
          registry-user: ${{ secrets.QUAY_IO_CLUSTERSCANNER_USERNAME }}
          registry-token: ${{ secrets.QUAY_IO_CLUSTERSCANNER_TOKEN }}

  build_imagecollector:
    needs: [changes, build_image_base]
    runs-on: ubuntu-latest
    # run on base image change
    # do not execute for PRs that origin from forks due to security concerns and missing secrets
    if: |
      (github.event_name == 'schedule') ||
      (always() &&
      (needs.build_image_base.result == 'success' ||
      (needs.build_image_base.result == 'skipped' && needs.changes.outputs.imagecollector == 'true')) &&
      ! (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork))
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: ./.github/actions/build_image
        with:
          image-path: images/process/imagecollector
          image-name: cluster-image-scanner-imagecollector
          registry-user: ${{ secrets.QUAY_IO_CLUSTERSCANNER_USERNAME }}
          registry-token: ${{ secrets.QUAY_IO_CLUSTERSCANNER_TOKEN }}

  build_imagesourcefetcher:
    needs: [changes, build_image_base]
    runs-on: ubuntu-latest
    # run on base image change
    # do not execute for PRs that origin from forks due to security concerns and missing secrets
    if: |
      (github.event_name == 'schedule') ||
      (always() &&
      (needs.build_image_base.result == 'success' ||
      (needs.build_image_base.result == 'skipped' && needs.changes.outputs.imagesourcefetcher == 'true')) &&
      ! (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork))
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: ./.github/actions/build_image
        with:
          image-path: images/process/image-source-fetcher
          image-name: cluster-image-scanner-image-source-fetcher
          registry-user: ${{ secrets.QUAY_IO_CLUSTERSCANNER_USERNAME }}
          registry-token: ${{ secrets.QUAY_IO_CLUSTERSCANNER_TOKEN }}

  build_workflowrunner:
    needs: [changes, build_image_base]
    runs-on: ubuntu-latest
    # run on base image change
    # do not execute for PRs that origin from forks due to security concerns and missing secrets
    if: |
      (github.event_name == 'schedule') ||
      (always() &&
      (needs.build_image_base.result == 'success' ||
      (needs.build_image_base.result == 'skipped' && needs.changes.outputs.workflowrunner == 'true')) &&
      ! (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork))
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: ./.github/actions/build_image
        with:
          image-path: images/process/workflow-runner
          image-name: cluster-image-scanner-workflow-runner
          registry-user: ${{ secrets.QUAY_IO_CLUSTERSCANNER_USERNAME }}
          registry-token: ${{ secrets.QUAY_IO_CLUSTERSCANNER_TOKEN }}

  build_dependencycheck:
    needs: [changes, build_image_base]
    runs-on: ubuntu-latest
    # run on base image change
    # do not execute for PRs that origin from forks due to security concerns and missing secrets
    if: |
      (github.event_name == 'schedule') ||
      (always() &&
      (needs.build_image_base.result == 'success' ||
      (needs.build_image_base.result == 'skipped' && needs.changes.outputs.dependencycheck == 'true')) &&
      ! (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork))
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: ./.github/actions/build_image
        with:
          image-path: images/scan/dependency-check
          image-name: cluster-image-scanner-scan-dependency-check
          registry-user: ${{ secrets.QUAY_IO_CLUSTERSCANNER_USERNAME }}
          registry-token: ${{ secrets.QUAY_IO_CLUSTERSCANNER_TOKEN }}

  build_distroless:
    needs: [changes, build_image_base]
    runs-on: ubuntu-latest
    # run on base image change
    # do not execute for PRs that origin from forks due to security concerns and missing secrets
    if: |
      (github.event_name == 'schedule') ||
      (always() &&
      (needs.build_image_base.result == 'success' ||
      (needs.build_image_base.result == 'skipped' && needs.changes.outputs.distroless == 'true')) &&
      ! (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork))
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: ./.github/actions/build_image
        with:
          image-path: images/scan/distroless
          image-name: cluster-image-scanner-scan-distroless
          registry-user: ${{ secrets.QUAY_IO_CLUSTERSCANNER_USERNAME }}
          registry-token: ${{ secrets.QUAY_IO_CLUSTERSCANNER_TOKEN }}

  build_lifetime:
    needs: [changes, build_image_base]
    runs-on: ubuntu-latest
    # run on base image change
    # do not execute for PRs that origin from forks due to security concerns and missing secrets
    if: |
      (github.event_name == 'schedule') ||
      (always() &&
      (needs.build_image_base.result == 'success' ||
      (needs.build_image_base.result == 'skipped' && needs.changes.outputs.lifetime == 'true')) &&
      ! (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork))
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: ./.github/actions/build_image
        with:
          image-path: images/scan/lifetime
          image-name: cluster-image-scanner-scan-lifetime
          registry-user: ${{ secrets.QUAY_IO_CLUSTERSCANNER_USERNAME }}
          registry-token: ${{ secrets.QUAY_IO_CLUSTERSCANNER_TOKEN }}

  build_runasroot:
    needs: [changes, build_image_base]
    runs-on: ubuntu-latest
    # run on base image change
    # do not execute for PRs that origin from forks due to security concerns and missing secrets
    if: |
      (github.event_name == 'schedule') ||
      (always() &&
      (needs.build_image_base.result == 'success' ||
      (needs.build_image_base.result == 'skipped' && needs.changes.outputs.runasroot == 'true')) &&
      ! (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork))
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: ./.github/actions/build_image
        with:
          image-path: images/scan/runasroot
          image-name: cluster-image-scanner-scan-runasroot
          registry-user: ${{ secrets.QUAY_IO_CLUSTERSCANNER_USERNAME }}
          registry-token: ${{ secrets.QUAY_IO_CLUSTERSCANNER_TOKEN }}

  build_new-version:
    needs: [changes, build_image_base]
    runs-on: ubuntu-latest
    # run on base image change
    # do not execute for PRs that origin from forks due to security concerns and missing secrets
    if: |
      (github.event_name == 'schedule') ||
      (always() &&
      (needs.build_image_base.result == 'success' ||
      (needs.build_image_base.result == 'skipped' && needs.changes.outputs.new-version == 'true')) &&
      ! (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork))
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: ./.github/actions/build_image
        with:
          image-path: images/scan/new-version
          image-name: cluster-image-scanner-scan-new-version
          registry-user: ${{ secrets.QUAY_IO_CLUSTERSCANNER_USERNAME }}
          registry-token: ${{ secrets.QUAY_IO_CLUSTERSCANNER_TOKEN }}

  build_malware:
    needs: [changes, build_image_base]
    runs-on: ubuntu-latest
    # run on base image change
    # do not execute for PRs that origin from forks due to security concerns and missing secrets
    if: |
      (github.event_name == 'schedule') ||
      (always() &&
      (needs.build_image_base.result == 'success' ||
      (needs.build_image_base.result == 'skipped' && needs.changes.outputs.malware == 'true')) &&
      ! (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork))
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: ./.github/actions/build_image
        with:
          image-path: images/scan/malware
          image-name: cluster-image-scanner-scan-malware
          registry-user: ${{ secrets.QUAY_IO_CLUSTERSCANNER_USERNAME }}
          registry-token: ${{ secrets.QUAY_IO_CLUSTERSCANNER_TOKEN }}

  build_syft:
    needs: [changes, build_image_base]
    runs-on: ubuntu-latest
    # run on base image change
    # do not execute for PRs that origin from forks due to security concerns and missing secrets
    if: |
      (github.event_name == 'schedule') ||
      (always() &&
      (needs.build_image_base.result == 'success' ||
      (needs.build_image_base.result == 'skipped' && needs.changes.outputs.syft == 'true')) &&
      ! (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork))
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: ./.github/actions/build_image
        with:
          image-path: images/scan/syft
          image-name: cluster-image-scanner-scan-syft
          registry-user: ${{ secrets.QUAY_IO_CLUSTERSCANNER_USERNAME }}
          registry-token: ${{ secrets.QUAY_IO_CLUSTERSCANNER_TOKEN }}

  build_notifier:
    needs: [changes, build_image_base]
    runs-on: ubuntu-latest
    # run on base image change
    # do not execute for PRs that origin from forks due to security concerns and missing secrets
    if: |
      (github.event_name == 'schedule') ||
      (always() &&
      (needs.build_image_base.result == 'success' ||
      (needs.build_image_base.result == 'skipped' && needs.changes.outputs.notifier == 'true')) &&
      ! (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork))
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: ./.github/actions/build_image
        with:
          image-path: images/process/notifier
          image-name: cluster-image-scanner-notifier
          registry-user: ${{ secrets.QUAY_IO_CLUSTERSCANNER_USERNAME }}
          registry-token: ${{ secrets.QUAY_IO_CLUSTERSCANNER_TOKEN }}

  test_minikube:
    needs:
      [
        build_workflowrunner,
      ]
    if: "${{ (github.event_name == 'schedule') || (needs.changes.outputs.base == 'true' && !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork)) }}"
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@master          
      - name: setup, execute and run test
        env:
          DD_TOKEN_SECRET: "${{secrets.DD_TOKEN_SECRET}}"
          DD_URL_PLACEHOLDER: "${{secrets.DD_URL_PLACEHOLDER}}"
          DD_USER_PLACEHOLDER: "${{secrets.DD_USER_PLACEHOLDER}}"
          SLACK_CLI_TOKEN_SECRET: "${{secrets.SLACK_CLI_TOKEN_SECRET}}"
          DEPSCAN_DB_DRIVER_PLACEHOLDER: "${{secrets.DEPSCAN_DB_DRIVER_PLACEHOLDER}}"
          DEPSCAN_DB_USERNAME_PLACEHOLDER: "${{secrets.DEPSCAN_DB_USERNAME_PLACEHOLDER}}"
          DEPSCAN_DB_CONNECTSRING_PLACEHOLDER: "${{secrets.DEPSCAN_DB_CONNECTSRING_PLACEHOLDER}}"
          DEPSCAN_DB_PASSWORD_PLACEHOLDER: "${{secrets.DEPSCAN_DB_PASSWORD_PLACEHOLDER}}"
        run: |
          pwd
          ls
          cd test_actions
          ./setup.bash
