name: Build Test Image

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build_test-image:
    runs-on: ubuntu-latest
    # run on base image change
    # do not execute for PRs that origin from forks due to security concerns and missing secrets
    if: |
      (github.event_name == 'schedule' && github.ref == 'master') ||
      (always() &&
      (needs.build_image_base.result == 'success' ||
      (needs.build_image_base.result == 'skipped' && needs.changes.outputs.notifier == 'true')) &&
      ! (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork))
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: ./.github/actions/build_image
        with:
          image-path: images/process/test-image
          image-name: cluster-image-scanner-test-image
          registry-user: ${{ secrets.QUAY_IO_CLUSTERSCANNER_USERNAME }}
          registry-token: ${{ secrets.QUAY_IO_CLUSTERSCANNER_TOKEN }}