name: Build Test Image

on:
  push:
#    branches:
#      - master
  pull_request:
  workflow_dispatch:

jobs:
  build_test-image:
    runs-on: ubuntu-latest
    # run on base image change
    # do not execute for PRs that origin from forks due to security concerns and missing secrets
#    if: |
#      (github.event_name == 'schedule') ||
#      (always() &&
#      (needs.build_image_base.result == 'success' ||
#      (needs.build_image_base.result == 'skipped' && needs.changes.outputs.notifier == 'true')) &&
#      ! (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork))
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - uses: ./.github/actions/build_image
        with:
          image-path: images/process/test-image
          image-name: cluster-image-scanner-test-image
          registry-user: ${{ secrets.QUAY_IO_CLUSTERSCANNER_USERNAME }}
          registry-token: ${{ secrets.QUAY_IO_CLUSTERSCANNER_TOKEN }}
